trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: FlutterInstall@0
  name: InstallFlutter
  displayName: Install flutter
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'
- task: FlutterCommand@0
  inputs:
    projectDirectory: '.'
    arguments: 'pub run build_runner build --delete-conflicting-outputs'
- task: FlutterBuild@0
  name: BuildFlutter
  displayName: Build flutter
  inputs:
    target: 'web'
    projectDirectory: '.'
