name: simple_auth_flutter_riverpod
description: Simple authentication flow using Flutter & Riverpod

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router:
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.2.1
  rxdart: ^0.27.3
  dio: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.2
  pin_code_fields: ^7.4.0
  fpdart: ^0.4.1
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.2.18
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  image_picker: ^0.8.7
  image_picker_for_web: ^2.1.12
  flutter_form_builder: ^7.8.0
  form_builder_phone_field: ^1.3.0
  form_builder_validators: ^8.5.0
  form_builder_extra_fields: ^8.5.0
  phone_number: ^0.12.0+2
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  flutter_google_places_hoc081098: ^1.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  go_router_builder:
  riverpod_generator: ^1.1.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
