name: simple_auth_flutter_riverpod
description: Simple authentication flow using Flutter & Riverpod

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router:
  flutter_riverpod:
  riverpod_annotation:
  rxdart: ^0.27.3
  dio: ^5.0.0
  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  go_router_builder:
  riverpod_generator:
  freezed: ^2.3.2

flutter:
  uses-material-design: true
