name: the_helper
description: A flutter project aimed at managing volunteer work and organizations

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.5
  go_router:
  flutter_riverpod:
  riverpod_annotation:
  flutter_hooks:
  hooks_riverpod:
  rxdart: ^0.27.3
  dio: ^5.3.2
  http_parser: ^4.0.2
  mime: ^1.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  fpdart: ^1.0.0
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.3.1
  jwt_decoder: ^2.0.1
  intl:
  image_picker: 
  image_picker_for_web:
  flutter_typeahead: 
  flutter_form_builder: 
  form_builder_phone_field: 
  form_builder_validators: 
  form_builder_extra_fields: 
  form_builder_image_picker: 
  phone_number: 
  phone_form_field:
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.3
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  infinite_scroll_pagination: ^3.2.0
  riverpod_infinite_scroll:
  cross_file:
  path:
  path_provider:
  flutter_cache_manager:
  cached_network_image:
  flutter_quill: ^7.4.1
  flutter_quill_extensions:
  vsc_quill_delta_to_html:
  image_cropper:
  country_picker:
  file_picker:
  avatar_stack: ^1.2.0
  expandable_text: ^2.3.0
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  collection: 
  crop_your_image: ^0.7.5
  sliver_tools: ^0.2.12
  im_stepper: 
  fuzzywuzzy: ^1.1.6
  after_layout:
  flutter_local_notifications:
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  fl_chart: ^0.63.0
  socket_io_client: ^2.0.3+1
  logging: ^1.2.0
  logger:
  mocktail: ^1.0.0
  envied: ^0.3.0+3
  fast_immutable_collections: ^9.1.5
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  build_runner:
  go_router_builder:
  riverpod_generator:
  riverpod_lint:
  custom_lint:
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'roboto'
      fonts: 
        - asset: 'assets/fonts/Roboto-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/Roboto-ThinItalic.ttf'
          style: italic
          weight: 100
        - asset: 'assets/fonts/Roboto-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Roboto-LightItalic.ttf'
          style: italic
          weight: 300
        - asset: 'assets/fonts/Roboto-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Roboto-Italic.ttf'
          weight: 400
          style: italic
        - asset: 'assets/fonts/Roboto-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Roboto-MediumItalic.ttf'
          weight: 500
          style: italic
        - asset: 'assets/fonts/Roboto-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Roboto-BoldItalic.ttf'
          weight: 700
          style: italic
        - asset: 'assets/fonts/Roboto-Black.ttf'
          weight: 900
        - asset: 'assets/fonts/Roboto-BlackItalic.ttf'
          weight: 900
          style: italic
        

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png

flutter_launcher_icons:
  android: true
  web: 
    generate: true
  image_path: "assets/images/rounded_logo.png"