name: the_helper
description: Simple authentication flow using Flutter & Riverpod

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router:
  flutter_riverpod:
  riverpod_annotation:
  rxdart: ^0.27.3
  dio: ^5.0.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.2
  pin_code_fields: ^7.4.0
  fpdart: ^0.6.0
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.2.18
  jwt_decoder: ^2.0.1
  intl: 
  image_picker: ^0.8.7
  image_picker_for_web: ^2.1.12
  flutter_typeahead: 
  flutter_form_builder: 
  form_builder_phone_field: 
  form_builder_validators: 
  form_builder_extra_fields: 
  phone_number: 
  phone_form_field:
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  flutter_google_places_hoc081098: ^1.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  infinite_scroll_pagination: ^3.2.0
  cross_file:
  flutter_cache_manager:
  cached_network_image: ^3.2.3
  flutter_quill: 
  image_cropper:
  country_picker:
  file_picker:
  back_button_interceptor:
  avatar_stack: ^1.2.0
  google_fonts: ^4.0.3
  expandable_text: ^2.3.0
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  collection: 
  form_builder_image_picker: 
  crop_your_image: ^0.7.4
  sliver_tools: ^0.2.10
  im_stepper: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.1
  build_runner:
  go_router_builder:
  riverpod_generator:
  riverpod_lint:
  custom_lint:
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'roboto'
      fonts: 
        - asset: 'assets/fonts/Roboto-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/Roboto-ThinItalic.ttf'
          style: italic
          weight: 100
        - asset: 'assets/fonts/Roboto-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Roboto-LightItalic.ttf'
          style: italic
          weight: 300
        - asset: 'assets/fonts/Roboto-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Roboto-Italic.ttf'
          weight: 400
          style: italic
        - asset: 'assets/fonts/Roboto-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Roboto-MediumItalic.ttf'
          weight: 500
          style: italic
        - asset: 'assets/fonts/Roboto-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Roboto-BoldItalic.ttf'
          weight: 700
          style: italic
        - asset: 'assets/fonts/Roboto-Black.ttf'
          weight: 900
        - asset: 'assets/fonts/Roboto-BlackItalic.ttf'
          weight: 900
          style: italic
        

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
